config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'users', to: 'users#index', as: :users
  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/posts', to: 'posts#index', as: :posts
  get 'users/:id/posts/:id', to: 'posts#show', as: :post
  get 'new_post', to: 'posts#new', as: :new_post
  post 'new_post', to: 'posts#create', as: :create_post
  resources :posts, only: %i[show new create] do
    member do
      post 'like'
    end
    resources :comments, only: [:create]
  end
end

app/models/Comments_Controller.rb
class CommentsController < ApplicationController
  before_action :find_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      render 'posts/show'
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_user_post_counter

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_user_post_counter
    user.update(posts_counter: user.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.first
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @post, notice: 'Comment was successfully created.'
    else
      render 'posts/show'
    end
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
# aplicación/controladores/comments_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show like]

  def index
    @user = User.find(params[:id])
    @posts = @user.posts
    @comments = Comment.where(user_id: params[:user_id])
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def like
    @post.increment!(:likes_counter)
    redirect_to @post
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @posts = Post.where(author_id: params[:user_id])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppMcv</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
  <% content_for :stylesheets do %>
  <%= stylesheet_link_tag "posts" %>
<% end %>

<div class="Users-Container">
  <img class="Users-img" src="https://cdn-icons-png.flaticon.com/128/3177/3177440.png"/>
  <div class="User-Text-Container">
    <h2 class="Username"><%= @user.name %></h2>
    <h3 class="Post-Container">Posts: <%= @user.posts_counter.zero? ? '0' : @user.posts_counter %></h3>
  </div>
</div>

<div class="post-container">
<% if @posts.present? %>
  <% @posts.each do |post| %>
    <div class="post">
      <%= link_to post_path(post) do %>
        <h2 class="txt"><%= post.title %></h2>
      <div class="User-Text">
        <p class="post-txt"><%= truncate(post.text, length: 30) %></p>
        <div class="counters">
        <p class="txt">Likes: <%= post.likes_counter %></p>
        <p class="txt">Comments: <%= post.comments_counter %></p>
        </div>
      </div>
      <% end %>
    </div>
<div class="post">
  <% if post.comments.present? %>
    <% post.comments.each do |comment| %>
     <p class="txt"><strong class="txt"><%= comment.user.name %>:</strong> <%= comment.content %></p>
    <% end %>
    <% else %>
     <p class="txt">There are no comments</p>
    <% end %>
  </div>
  <% end %>
<% else %>
  <p class="txt">There are no comments.</p>
<% end %>
</div>
<div class="button-container">
  <%= link_to "New Post", new_post_path, class: "button-posts" %>
  <%= link_to "Pagination", users_path, class: "button-posts" %>
</div>

app/views/posts/new.html.erb
<!-- app/views/posts/new.html.erb -->
<h1>Create a New Post</h1>

<%= form_with(model: @post, url: new_post_path(current_user), method: :post) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit "Create Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "post" %>
<% end %>

<div class="User-Text">
  <div class="title-and-counters">
    <div class="tittle-users">
      <h1 class="post-txt"><%= @post.title %></h1>
      <p class="post-txt">by: <%= @post.user.name %></p>
    </div>
    <div class="counters">
      <p class="post-txt">Likes: <%= @post.likes_counter %></p>
      <p class="post-txt">Comments: <%= @post.comments_counter %></p>
    </div>
  </div>
  <p class="post-content"><%= @post.text %></p>
</div>

<%= button_to "Like", like_post_path(@post), method: :post, remote: true, class: "like-button" %>

<%= form_with(model: [@post, Comment.new], remote: true) do |form| %>
  <div class="field">
    <%= form.text_area :content, placeholder: "Add a comment..." %>
  </div>
  <div class="actions">
    <%= form.submit "Post Comment" %>
  </div>
<% end %>

<div class="comments">
  <% if @post.comments.present? %>
    <% @post.comments.each do |comment| %>
      <p class="txt"><strong class="txt"><%= comment.user.name %>:</strong> <%= comment.content %></p>
    <% end %>
  <% else %>
    <p class="txt">There are no comments.</p>
  <% end %>
</div>

app/views/users/index.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "users" %>
<% end %>

<div class="users">
  <% if @users.present? %>
    <% @users.each do |user| %>
      <%= link_to user_path(user.id) do %>
        <div class="Users-Container">
          <img class="Users-img" src="https://cdn-icons-png.flaticon.com/128/3177/3177440.png"/>
          <div class="User-Text-Container">
          <h2 class="Username"><%= user.name %></h2>
          <h3 class="Post-Container">Posts: <%= user.posts_counter.zero? ? '0' : user.posts_counter %></h3>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <p>There are no users available.</p>
  <% end %>
</div>

app/views/users/show.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag "user" %>
<% end %>

<div class="users">
  <% if @posts.present? %>
    <% user = @posts.first.user %>
    <div class="Users-Container">
      <img class="Users-img" src="https://cdn-icons-png.flaticon.com/128/3177/3177440.png"/>
      <div class="User-Text-Container">
        <h1 class="Username"><%= user.name %></h1>
        <h3 class="Post-Container">Posts: <%= user.posts_counter.zero? ? '0' : user.posts_counter %></h3>
      </div>
    </div>
    <div class="txt-Container">
      <h2 class="txt">Bio:</h2>
      <h3 class="txt">This is a generic example for the user's Bio</h3>
    </div>
    <% @posts.each do |post| %>
      <div class="txt-Container">
        <%= link_to posts_path(post) do %>
          <h2 class="txt">Post # <%= post.id %></h2>
          <h2 class="txt"><%= post.title %></h2>
        <% end %>
      </div>
    <% end %>
    <div class="button-container">
    <button type="button" class="button-posts"><%= link_to "See all posts", posts_path %></button>
    </div>
  <% else %>
    <p>There are no posts available.</p>
  <% end %>
</div>